#!/usr/bin/env python3
from ninja import Writer
from pathlib import Path


WORKING_DIR = Path(__file__).parent
NINJA_OUT = WORKING_DIR / "build.ninja"


def generate(file: object) -> None:
    writer = Writer(file, width=80)
    writer.comment("This file is generated by configure.py. Do not edit it directly.")


if __name__ == "__main__":
    file = open(NINJA_OUT, "w")
    generate(file)
    file.close()
